stages:
  - build
  - release

build:linux:
  stage: build
  image: node:14
  script:
    - npm install
    - npm run build:linux
  artifacts:
    paths:
      - dist/  # Adjust this path to where your Linux build artifacts are located

build:win:
  stage: build
  image: electronuserland/builder:wine
  script:
    - npm install
    - npm run build:win
  artifacts:
    paths:
      - dist/  # Adjust this path to where your Windows build artifacts are located

release:
  stage: release
  image: node:14
  script:
    - echo "Creating release for $CI_COMMIT_TAG"
    - |
      ASSET_URL="https://gitlab.com/your_project/-/jobs/$CI_JOB_ID/artifacts/download"
      RESPONSE=$(curl --silent --write-out "HTTPSTATUS:%{http_code}" --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
           --data "name=Release $CI_COMMIT_TAG" \
           --data "tag_name=$CI_COMMIT_TAG" \
           --data "description=Release for version $CI_COMMIT_TAG" \
           --data "assets[links][]=name=Asset&url=$ASSET_URL" \
           "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/releases")
      
      # Get the body and the status code
      BODY=$(echo "$RESPONSE" | sed -e 's/HTTPSTATUS\:.*//g')
      STATUS=$(echo "$RESPONSE" | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')

      # Check if the request was successful
      if [ "$STATUS" -ne 201 ]; then
        echo "Failed to create release: $STATUS"
        echo "Response: $BODY"
        exit 1
      else
        echo "Release created successfully!"
      fi
  only:
    - tags

