image: node:14

stages:
  - build

variables:
  ELECTRON_CACHE: "$CI_PROJECT_DIR/.cache/electron"
  ELECTRON_BUILDER_CACHE: "$CI_PROJECT_DIR/.cache/electron-builder"

before_script:
  - npm install -g electron-builder
  - apt-get update
  - apt-get install -y wine
build_macos:
  stage: build
  script:
    - npm install
    - npm run build:mac
    - electron-builder --mac --x64
  artifacts:
    paths:
      - dist/*.dmg
      - dist/*.zip
  only:
    - main

build_windows:
  stage: build
  tags:
    - windows
  script:
    - npm install
    - apt-get install wine
    - npm run build:win
    - electron-builder --win --x64
  artifacts:
    paths:
      - dist/*.exe
      - dist/*.zip
  only:
    - main

build_linux:
  stage: build
  script:
    - npm install
    - npm run build:linux
    - electron-builder --linux --x64
  artifacts:
    paths:
      - dist/*.AppImage
      - dist/*.deb
      - dist/*.rpm
  only:
    - main
