stages:
  - build
  - release

build:
  stage: build
  image: node:14
  script:
    - npm install
    - npm run build:linux
    - npm run build:win
  artifacts:
    paths:
      - dist/  # Adjust this path to where your build artifacts are located

release:
  stage: release
  image: node:14
  script:
    - echo "Creating release for $CI_COMMIT_TAG"
    - |
      curl --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
           --data "name=Release $CI_COMMIT_TAG" \
           --data "tag_name=$CI_COMMIT_TAG" \
           --data "description=Release for version $CI_COMMIT_TAG" \
           --data "assets[links][]=name=Asset&url=https://gitlab.com/your_project/-/jobs/$CI_JOB_ID/artifacts/download" \
           "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/releases"
  only:
    - tags
